# Created by trellis-cli v0.9.2
# Documentation: https://roots.io/trellis/docs/vault/

vault_mysql_root_password: "SdloPYDYTvXVvGBSkQZXKXcd29yg4ZCfDgBNhcoHTkJJpzAGdpqoyGLB7hgXCvdn"
vault_wordpress_sites:
  example.test:
    admin_password: "qtGuucTDZ6amXYO0nMcDM50Pni7gThyZaxsFEADdEBt24HTR6bDTSyTq9zBmmXg1"
    env:
      db_password: "2bSRNkvtuBpudjwjIQOb6NQy4RAr0ERWPohImVZfWoxPCw9zECwMXQ3OoqjXQR09"
      auth_key: "oRKeUqdXPj6sL0VIwJ56sj7Qo91Rb0LNuyHtliBNy8CgwfXsJEebhJdgdg1GnK8E"
      secure_auth_key: "v709gjv76ln1M6QFOWF0ISpeILxN1upSqCEJ4dwbxtLdCj6FDsgD3zedykAKaNk3"
      logged_in_key: "ek1be29bkhMjvS8ZIBTzvaFcVZ8nRwb6NcJTqRG9bUltTGK33NGaxitrlxTbYsYD"
      nonce_key: "5FuKD19sW53RdkXkcoAAWG1t3Gq2GVx8bfEuxwMUdGhu4hVYD9Ju2lcjjwzbagVw"
      auth_salt: "rdBJsLi3kT1hsimpOXG907fefLgqASR2l1qPmZsWuVIZc8njbm0a3jCiD2MBEa44"
      secure_auth_salt: "a0BPlSaXlutjSk79db0VuKkGk0n0P4tfAhGgnkyOhTrSJcOfyzUhZ3qFCLjnxVVz"
      logged_in_salt: "zn8f3DxmAeQTysaEsENXcSxCAfOsvZCjmdfsBCVlNgFjwOiMTQjDn537G2vGbXhq"
      nonce_salt: "DvQl1ISI0ebi45hUEA8j2vRFWj7CIp28byhtTNi0PhsnBuw4GgguDJtnepXpceG0"
