# Created by trellis-cli v0.9.2
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  example.test:
    site_hosts:
    - canonical: example.test
      redirects:
      - www.example.test
    local_path: ../site
    admin_email: admin@example.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
